'use client';

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Button } from '@/components/button';
import { Nav } from '@/components/nav';
import { ServiceList } from '@/components/service-list';
import { AppQueriesProvider } from '@/hooks/app-queries';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Uptime',
//   description: 'Generated by create next app',
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: Infinity,
      refetchOnMount: false,
      refetchOnWindowFocus: false,
      refetchOnReconnect: true,
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <QueryClientProvider client={queryClient}>
        <AppQueriesProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} flex flex-col gap-4 bg-background text-foreground transition-colors duration-200 accent-up antialiased`}
          >
            <Nav />
            <main className='grid grid-cols-[2fr_5fr] p-4 gap-4'>
              <section className='flex flex-col gap-4'>
                <Button className='me-auto'>Add New Monitor</Button>
                <ServiceList />
              </section>
              {children}
            </main>
          </body>
        </AppQueriesProvider>
      </QueryClientProvider>
    </html>
  );
}
