import { createInsertSchema } from 'drizzle-zod';
import z from 'zod';
import {
  groupTable,
  type groupToNotifierTable,
  type historyTable,
  type keyValTable,
  notifierTable,
  serviceTable,
  type stateTable,
  tagTable,
} from '@/lib/drizzle/schema';
import { monitorParamsSchema } from '@/lib/monitor/schema';
import { notifierParamsSchema } from '@/lib/notifier/schema';
import type { ServiceStatus } from '@/lib/types';

// autogenerated zod schemas do not include default values

export const notifierUpdateSchema = createInsertSchema(notifierTable)
  .omit({
    createdAt: true,
    updatedAt: true,
  })
  .extend({
    id: z.int().min(1),
    params: notifierParamsSchema,
  });

export const notifierInsertSchema = notifierUpdateSchema
  .omit({
    id: true,
  })
  .extend({
    active: z.boolean().default(true),
  });

export type NotifierUpdate = z.infer<typeof notifierUpdateSchema>;
export type NotifierInsert = z.infer<typeof notifierInsertSchema>;
export type NotifierSelect = (typeof notifierTable)['$inferSelect'];

export const groupInsertSchema = createInsertSchema(groupTable)
  .omit({ createdAt: true, updatedAt: true, id: true, renotifySeconds: true })
  .extend({ name: z.string().min(1), renotifySeconds: z.int().min(60).optional() });

export type GroupInsert = z.infer<typeof groupInsertSchema>;
export type GroupSelect = (typeof groupTable)['$inferSelect'];

type GroupToNotifierTable = typeof groupToNotifierTable;
export type GroupToNotifierInsert = GroupToNotifierTable['$inferInsert'];
export type GroupToNotifierSelect = GroupToNotifierTable['$inferSelect'];

export const serviceUpdateSchema = createInsertSchema(serviceTable)
  .omit({
    createdAt: true,
    updatedAt: true,
    id: true,
  })
  .extend({
    id: z.int(),
    groupId: z.int().min(1).default(1),
    name: z.string().min(1),
    active: z.boolean().default(true),
    checkSeconds: z.int().min(60).default(300),
    failuresBeforeDown: z.int().min(0).default(3),
    retainCount: z.int().min(0).default(8640),
    params: monitorParamsSchema,
  });
export const serviceInsertSchema = serviceUpdateSchema.omit({ id: true });
export type ServiceUpdate = z.infer<typeof serviceUpdateSchema>;
export type ServiceInsert = z.infer<typeof serviceInsertSchema>;
export type ServiceSelect = (typeof serviceTable)['$inferSelect'];

export const tagUpdateSchema = createInsertSchema(tagTable).required();
export const tagInsertSchema = tagUpdateSchema.omit({ id: true });
export type TagUpdate = z.infer<typeof tagUpdateSchema>;
export type TagInsert = z.infer<typeof tagInsertSchema>;
export type TagSelect = (typeof tagTable)['$inferSelect'];

type HistoryTable = typeof historyTable;
export type HistoryInsert = HistoryTable['$inferInsert'];
export type HistorySelect = HistoryTable['$inferSelect'];
export interface HistorySummarySelect extends HistorySelect {
  name: string;
}
export interface MiniHistory {
  from: Date;
  to: Date;
  items: { id: number; status: ServiceStatus; latency?: number }[];
}

type StateTable = typeof stateTable;
export type StateInsert = StateTable['$inferInsert'];
export type StateSelect = StateTable['$inferSelect'];

export interface ServiceWithState extends ServiceSelect {
  state: StateSelect | null;
}

type KeyValTable = typeof keyValTable;
export type KeyValInsert = KeyValTable['$inferInsert'];
export type KeyValSelect = KeyValTable['$inferSelect'];
